In [1]:
addprocs(5);

## Fonctions

* __remotecall(f, id::Integer, args...; kwargs...)__ : Appelez une fonction de manière asynchrone sur les arguments donnés sur le processus spécifié. Renvoie un Futur. Les arguments suivant, le cas échéant, sont transmis à la fonction.
* __fetch(c::Channel)__ : Attend et obtient le premier article disponible du Channel. Ne supprime pas l'élément.
* __remotecall_fetch(f, id::Integer, args...; kwargs...)__ : Performe un remotecall() et un fetch() immédiatement.
* __pmap(f, c)__ : Transforme une collection c en appliquant une fonction f sur chaque element en utilisant les processus disponibles.

In [2]:
r = remotecall(rand, 2, 2, 2)
r_f = fetch(r)

2×2 Array{Float64,2}:
 0.559155  0.419005
 0.536324  0.208399

In [3]:
remotecall_fetch(getindex, 2, r_f, 1, 1)

0.5591548830538178

In [4]:
M = Matrix{Float64}[rand(1000,1000) for i = 1:10];
pmap(mean, M)

10-element Array{Float64,1}:
 0.500091
 0.500554
 0.500081
 0.500089
 0.500078
 0.499715
 0.499197
 0.500212
 0.499945
 0.499723

## Macros
* __@spawnat__ : Accepte deux arguments, un processus p et une expression. Une Closure est créé autour de l'expression et est exécuté async sur le processus p. Retourne un Future vers le résultat.
* __@everywhere__ : Exécute une expression dans tous les processus.
* __@parallel__ : Exécute un for loop sur différent processus en distribuant chaque loop. peut etre accompagné d'une fonction de réduction.

In [5]:
s = @spawnat 2 2 .* r_f
fetch(s)

2×2 Array{Float64,2}:
 1.11831  0.838011
 1.07265  0.416799

In [6]:
@everywhere function f(x)
    x^2
end

@everywhere Z = [1 2 3; 1 2 3; 1 2 3]
Z

3×3 Array{Int64,2}:
 1  2  3
 1  2  3
 1  2  3

In [7]:
nheads = @parallel (+) for i = 1:200000000
    Int(rand(Bool))
end

100005330

In [8]:
a = zeros(10)
@parallel for i = 1:10
    a[i] = i
end

a

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [9]:
a = SharedArray{Float64}(10)
@parallel for i = 1:10
    a[i] = i
end

a

10-element SharedArray{Float64,1}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

In [10]:
# read-only
a = randn(1000)
@parallel (+) for i = 1:10
    f(a[rand(1:end)])
end

11.616284270256784

# Communication
* __Channel{T}(sz)__ : Construit un Channel avec un tampon interne qui permet de contenir un nombre sz d'items de type T. Insérer avec put! et retirer avec take!. Si l'un ou l'autre est bloqué, il attend.

In [11]:
jobs = Channel{Int}(32);
results = Channel{Tuple}(32);

function do_work()
   for job_id in jobs
       exec_time = rand()
       sleep(exec_time)               
       put!(results, (job_id, exec_time))
   end
end;

function make_jobs(n)
   for i in 1:n
       put!(jobs, i)
   end
end;

n = 12;
@schedule make_jobs(n);

for i in 1:4 
   @schedule do_work()
end

@elapsed while n > 0
   job_id, exec_time = take!(results)
   println("$job_id terminé en $(round(exec_time,2)) secondes")
   n = n - 1
end;

3 terminé en 0.22 secondes
2 terminé en 0.24 secondes
1 terminé en 0.44 secondes
4 terminé en 0.56 secondes
6 terminé en 0.33 secondes
9 terminé en 0.07 secondes
8 terminé en 0.32 secondes
5 terminé en 0.76 secondes
7 terminé en 0.62 secondes
10 terminé en 0.6 secondes
11 terminé en 0.66 secondes
12 terminé en 0.81 secondes
